# Generated by Django 3.2.9 on 2021-11-13 16:19

from django.db import migrations, models
import my_app.validators.local_file_validator
import mysite.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', validators=[mysite.validators.global_file_validator, my_app.validators.local_file_validator.local_file_validatorX])),
            ],
        ),
    ]
